server:
  port: 8080


eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: pagamento
          uri: lb://PAGAMENTO #http://localhost:8082 isso vai conectar de acordo com o nome do client, lb de load balance
          predicates:
            - Path=/pagamento/**
        - id: crud
          uri: lb://CRUD	#http://localhost:8081
          predicates:
              - Path=/crud/**
  application:
    name: API-GATEWAY-PORTEIRO
