server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/DataBaseVendas?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 8718
